### ISSUE TITLE
How to configure the MediaUpload for isolated-block-editor?

### ISSUE THREAD

**Issue by ghost** [Automattic/isolated-block-editor#117]
any document about how to configure the MediaUpload for isolated-block-editor?

**Comment by johngodley** [comment]
Can you explain more about what you are trying to do and what problem you are seeing?

**Comment by adrianhm13** [comment]
Could u share how you could make MediaUpload work if its not too much trouble?

Thanks a lot!

**Comment by alextsoi** [comment]
@cnmade 
Here is my approach that I am going to do:
As I implemented this editor into a custom CMS admin panel, in my admin panel, I already had my own media library implemented as well, in order to provide better UX for admins to:
1. select uploaded image from library
2. uplaod directly and saved to media library
3.  insert from URL

I checked the code during the weekend, and found that 
isolated-block-editor repo has added addFilter on "editor.MediaUpload", which that component seems try to implement similar thing like you see in WordPress

Therefore, I try to addFilter as well in large priority, i.e. 11 > original's 10, such that during calling the image block, the existing callback implemented in this repo won't be called but my component will be called

<img width="607" alt="Screenshot 2022-07-24 at 1 10 16 PM" src="https://user-images.githubusercontent.com/16984543/180633277-0471060b-593a-4585-9037-f2c9dd3b83ff.png">

Then my MediaUpload is just return a button with onClick, this onClick handler will open my own media library.
I think this will work and I don't need to create a pull request / touch the existing repo

The remaining thing will be upload file directly (i.e. Upload button on the screencap)
I have not yet build the poc for that, but it shouldn't be too difficult because I already have my custom media library and corresponding file upload API.

As I am directly editing the code in storybook in this repo for testing, the code to make the screencap working will be something like below code. You can check below code as reference

I guess when you add the editor using below code
`let editor = <IsolatedBlockEditor
		settings={{
			editor: {
				mediaUpload: (whatIsThis) => {
					console.log(whatIsThis);
					return true
				},
				allowedMimeTypes: ['image/png'],
			}
		}}
	/>;
	addFilter('editor.MediaUpload', 'isolated-block-editor/media-upload', () => MyMediaUploader, 11);
	return editor;`


MyMediaUploader component:
`
function MyMediaUploader(props) {
	const { onSelect } = props;
	const test = () => {
		onSelect({
			id: 1,
			mime: 'image/png',
			tpye: 'image',
			subtype: 'png',
			url: 'https://via.placeholder.com/300/09f/fff.png',
			alt: '',
			link: 'https://google.com.hk',
			caption: 'test'
		})
	}
	return (
		<button className="components-button is-primary" onClick={test}>My Media Library</button>
	);
}
`

Forgive me if I didn't format the code, here is the preview
<img width="772" alt="Screenshot 2022-07-24 at 1 22 58 PM" src="https://user-images.githubusercontent.com/16984543/180633466-cd32c7c5-f635-4096-9615-11eda27b8cbd.png">

**More Update:**
If you add id property in onSelect(params), when you reopen the block editor after refreshing the page, it will throw an error ( because you need to handle the validation of image block, this means you need to further modify the API request )

**Comment by johngodley** [comment]
Following on from alextsoi, yes the `mediaUpload` setting is the way that Gutenberg passes responsibility to an external media library. In the case of WordPress itself you would need to ensure that the media library was loaded and present on the page:

`wp_enqueue_media();`

Then something like:

```js

import { mediaUpload } from '@wordpress/editor';

settings.editor.mediaUpload = mediaUpload;
```

If you're not using WP then you would need to essentially replicate `mediaUpload` in your own component.
