### ISSUE TITLE
UI buttons causes form submit

### ISSUE THREAD

**Issue by vonloxx** [Automattic/isolated-block-editor#197]
Hi, probably not in this project scope but here it goes anyway:
I'm using the isolated block editor inside a form and any UI button, for example changing the font size of a paragraph, will cause the parent form to submit. This is because the button component doesn't specify a type, like type="button".
Does anyone knows a workaround for this?
Thanks.

**Comment by johngodley** [comment]
I've seen the same thing too, yes. Fundamentally it seems like it's a 'bug' with Gutenberg - all buttons should be of type 'button' (unless they need to be 'submit') otherwise they will default to 'submit' and that's not good.

Until that is fixed, the way I've worked around it is to add an event listener to the form that stops the submit from propagating further:

```js
function insulateForm( form ) {
	form.addEventListener( 'submit', ( ev ) => {
		if ( ev.submitter && ev.submitter.closest( '.iso-editor' ) ) {
			ev.stopPropagation();
			ev.preventDefault();
		}
	} );
}
```

**Comment by vonloxx** [comment]
Hehe! Exactly the solution I've come up with. Thanks John.

**Comment by ciampo** [comment]
Opened https://github.com/WordPress/gutenberg/issues/46814 to track this in Gutenberg.
