### ISSUE TITLE
copy paste of image

### ISSUE THREAD

**Issue by mzwach** [Automattic/isolated-block-editor#216]
Hi,
this is a realy great project - I love it!

But it would so helpful to me, if I could get copy/paste of images (screen captures...) working.
In case that I past an image, I see the following lines in console:

`Received HTML:

 <empty string> [isolated-block-editor.js:9:389054](https://mz2.log2track.com/u/michi/js/gutenberg/isolated-block-editor.js)
Received plain text:

 <empty string> [isolated-block-editor.js:9:389097](https://mz2.log2track.com/u/michi/js/gutenberg/isolated-block-editor.js)
Received items:
 
Array [ File ]
[isolated-block-editor.js:9:389639](https://mz2.log2track.com/u/michi/js/gutenberg/isolated-block-editor.js)`

Afterwards this TypeError: w is not a funciton in [react-dom.production.min.js:121:178](https://unpkg.com/react-dom@18/umd/react-dom.production.min.js)

Is this not implemented yet or is my pure js installation not working?

Another realy essential question to me would be, whether it is feasible to get an customized upload destination implemented, without react and typescrpt? Is there a way to do it?

Thank you in advance,
Michael

**Comment by johngodley** [comment]
Can you do that in the core Gutenberg? This project just wraps Gutenberg so that's the place to start checking first - we don't really handle anything image related here.

I don't think typescript is needed for anything. The upload destination is determined by you when configuring this project: https://github.com/Automattic/isolated-block-editor#media-uploader

**Comment by johngodley** [comment]
Closing this for now, please reopen with more details.
