### ISSUE TITLE
Collab: Emoji can be rendered incorrectly

### ISSUE THREAD

**Issue by mirka** [Automattic/isolated-block-editor#40]
An incoming change that ends with an emoji can be rendered incorrectly until something else happens.

## Screen recording

<img src="https://user-images.githubusercontent.com/555336/129969827-a772776e-0468-4e2e-8fab-2a1a2fad8b8d.gif" alt="An emoji displays in the peer editor as two fallback glyphs" width="400">

**Comment by mirka** [comment]
This seems to be caused by how the peer caret is rendered.

**Comment by lamosty** [comment]
I'm trying to debug this and I noticed that:
1. this doesn't happen with all emojis;
2. what's interesting (or not) is that this also happens if you first send any message from one user (for example, typing "test") and then from the other user's editor you delete the first user's message and copy-paste an emoji, it still renders weirdly — so the problem is not in the transport layer

**Comment by lamosty** [comment]
~Another observation: it only happens if there are less than 5 characters. If 5 or more, emojis render fine.~

Update: depends on the caret position. If it renders before the caret, then it's rendered incorrectly. It always renders fine after.
![Screen Shot 2021-10-08 at 14 16 47](https://user-images.githubusercontent.com/4988512/136555479-84ec8a75-7ac8-495e-8ea1-ad1e04118f50.png)

**Comment by lamosty** [comment]
I'm not sure why but I noticed that if I used `span` for the caret instead of `mark`, I don't get the same problem and it looks to work fine. Try to replace the `mark` here with `span`: https://github.com/Automattic/isolated-block-editor/blob/e224be77640f400b1691a7a898522bb8d3d898c8/src/components/collaborative-editing/use-yjs/formats/collab-caret/index.js#L88 and try to repro the original issue.

Update: same problem if I update `mark` to `span` in https://github.com/Automattic/isolated-block-editor/blob/fbec1104bb368a4e47b32c1116e91683b0edb88d/src/components/collaborative-editing/use-yjs/formats/collab-caret/style.scss. Must be css or file related.

**Comment by lamosty** [comment]
Not sure if related, but if you delete an emoji, the editor throws an error and crashes:
![Screen Shot on 2021-10-15 at 15-39-09](https://user-images.githubusercontent.com/4988512/137496618-be79ac04-3cb3-4b7c-9387-fc215b867d5f.png)

I guess debugging that could help resolve this mystery.

**Comment by mirka** [comment]
> Not sure if related, but if you delete an emoji, the editor throws an error and crashes

The crashing is an upstream issue https://github.com/yjs/yjs/issues/303

I guess you could say the root cause is the same though (grapheme cluster handling).
