### ISSUE TITLE
Having to parse scss in the built module forces consumers to use a sass parser

### ISSUE THREAD

**Issue by samueljseay** [Automattic/isolated-block-editor#55]
Thanks so much for the effort you've put into isolated-block-editor! I was wondering if it would be possible to get a less opinionated build of the module that doesn't require things like a sass parser, and also doesn't force loading all the CSS via the component entry file.

There are 2 reasons I'm asking for this.

1. Building the scss to css would be more generically useful to any kind of build system, not forcing users to have webpack and a scss parser installed. Removing the need for consumers to have sass in their build toolchain will speed up builds for all consumers of the module at the cost of one slower build before publish.

2. On the project I'm working on to integrate isolated-block-editor, we're using Next.js and there is a long outstanding "feature/bug" of Next.js that it [won't load stylesheets from within node_modules](https://github.com/vercel/next.js/discussions/27953). This isn't the fault of isolated-block-editor, but it would help me work around this issue.

I also would be happy to take a stab at working on this effort, because it directly relates to something I'm working on at work, but I wanted to get your opinions first before contributing anything.

**Comment by johngodley** [comment]
The current build is based around Gutenberg itself, which uses a SASS parser, so it's just been easier to go with that.

A plain CSS file is produced (https://github.com/Automattic/isolated-block-editor/blob/trunk/build-browser/isolated-block-editor.css).

If you can't import this into Next.js what alternatives do you have in mind? Open to anything here! Doesn't Next.js use a SASS system of some kind?

**Comment by samueljseay** [comment]
@johngodley Next.js does indeed use a sass parser but the main issue is that it does not allow sass or css imports in node_modules (yet). The fix would be to distribute a version of the editor that doesn't import the css and requires loading it manually. If you're happy to have another distribution that does not import css in the JS then I'll be happy to contribute that.

**Comment by johngodley** [comment]
I'd like to avoid having a separate distribution if possible - it sounds like it would increase confusion - and would prefer a way to modify this one.

It seems like a problem other people must also face. For example, Gutenberg itself releases modules with CSS imports. Can these be imported into Next.js? If so, we can make whatever modifications are needed here. If they can't be imported then it's a bigger problem as even if you have a build of this repo that can be imported, you wouldn't be able to import the Gutenberg modules, and these will still needed in the build process.

As mentioned above, there is a full build that includes all the JS and CSS (this repo and all of Gutenberg) in one single file. It's included in the module and is available as an external resource (see bottom of https://github.com/Automattic/isolated-block-editor/releases/tag/2.4.1). These files require no build stage and have no further dependencies. If it's not possible to include Gutenberg modules because of the CSS then this might be a solution (or something similar, anyway).

Do you have any code, even if just an example, showing the problem? It'd be handy to have something to play around with.

**Comment by samueljseay** [comment]
@johngodley I did try the isolated build but there was a separate issue with that, that it looks for React on the window which won't work for my situation.

I am pretty sure I can put together some kind of minimal reproduction for you to explore. I'll get on to that.

> It seems like a problem other people must also face

Absolutely, and in fact users of tailwind and other major libs face this problem too. Its an opinionated decision on the part of Next.js imho and moving away from Next.js still may be the solution to my problem at this point. They do intend to fix it, but there is no timeline.

I agree overall that more distributions is not ideal, thanks for your feedback on that.

**Comment by samueljseay** [comment]
On our end we've decided to give up on Next.js rather than try and do this work. We're running into some other constraints with it so it makes sense on our end. I'll close this for now because I don't see myself getting the bandwidth to come up with a better solution.
