### ISSUE TITLE
Collab: Peer edits inside a Column or Group block appear glitchy

### ISSUE THREAD

**Issue by mirka** [Automattic/isolated-block-editor#60]
Peer edits inside a Column or Group block can appear glitchy when peer edits to another block are also being received at the same time. The data integrity is fine, but the peer caret and block selection flickers.

I'm guessing this is a performance issue.

## Steps to reproduce

1. Insert a Paragraph block in a Columns block. Outside of the Columns block, insert a normal Paragraph block.
2. Open three different clients.
3. In Client A, type in the normal Paragraph block. At the same time, in Client B type in the Columns ▸ Paragraph block.
4. Observe these peer changes from Client C.

https://user-images.githubusercontent.com/555336/133302989-07a75882-3e3f-4a89-b7bf-5135a98a9eda.mp4

**Comment by mtias** [comment]
Curious if there's an underlying reconciliation bug there. cc @youknowriad

**Comment by youknowriad** [comment]
It seems receiving external updates in block-editor package (update the `value` prop of BlockEditorProvider) can be a somewhat heavy operation. This is not something we optimize for in general in the editor since it doesn't happen in a regular session (no collaborative editing). 

The other possibility is that there's too much back and forth in the sync protocol because there are two many conflicts resulting in diffs and updates being sent back and forth too often.

**Comment by mirka** [comment]
I haven't looked into it yet, but my initial guess is that it has something to do with how innerBlocks are recursively processed (either in the Yjs–Gutenberg conversion or Gutenberg-side rendering). Top-level non-nested blocks don't flicker, both in the repro case above and also in situations with more concurrent peer edits, like 5+ peers typing at once.
