### ISSUE TITLE
Collab: changing the color of the text in a section changes the name in the label to that same color

### ISSUE THREAD

**Issue by zdenys** [Automattic/isolated-block-editor#63]
![image](https://user-images.githubusercontent.com/39308239/134511995-69d1123e-f54a-4591-afad-a671586acca8.png)

![image](https://user-images.githubusercontent.com/39308239/134512346-a7b3839b-66a5-4ce6-881d-43bf5ede0b2e.png)

![image](https://user-images.githubusercontent.com/39308239/134513489-d46cc683-8ffa-4253-ab0f-38a2c1006ff8.png)

![image](https://user-images.githubusercontent.com/39308239/134513511-ddc1b50e-aa17-44bb-8118-86ac511622d3.png)

---
Discovered as part of team testing p9ag8j-1D4-p2#comment-4081

**Comment by lamosty** [comment]
I'm not able to reproduce this locally in the Storybook. I think the reason could be that we only have the "Text color" format while WP.com has the "Highlight" one. /cc @mirka for ideas.

Update: I can repro on wpcom, it seems to be the Highlight format. Gonna dig deeper.

**Comment by lamosty** [comment]
I think the problem might be coming from https://github.com/Automattic/isolated-block-editor/commit/e224be77640f400b1691a7a898522bb8d3d898c8#diff-f35c76a5cd3eec9cfc906a48ced421438cea0abe2426c82e51fa32debc0a4a6cR13. If we use `currentColor` for `--iso-editor-collab-caret-label-text-color` in conjunction with text color, it will cascade the text color through `currentColor` to `--iso-editor-collab-caret-label-text-color` and thus to `::after` which displays the peer name. 

Shall we use some high contrast value instead of `currentColor` in low-contrast situations instead? Also, what's interesting is that this gets applied on WP.com while it doesn't on a Storybook. Not sure if the fn to calculate the contrast could be misbehaving here.

/cc @mirka 

This is an example html code:
```
<mark style="background-color: rgba(0, 0, 0, 0);" class="has-inline-color has-pale-pink-color" data-rich-text-format-boundary="true">
    efewfew fe
    <mark
        id="iso-editor-collab-caret-3abaaa56-aaa6-4a29-b5df-1ce09380af4a"
        class="iso-editor-collab-caret is-collapsed is-shifted"
        title="Rastislav Lamoš"
        style="--iso-editor-collab-caret-color: #aa72ee; --iso-editor-collab-caret-label-text-color: currentColor;"
    >
        w
    </mark>
</mark>
```

As you can see, the parent `mark` has `pale-pink` color and the child `mark` has `--iso-editor-collab-caret-label-text-color: currentColor` which seems to use the `pale-pink` one since `currentColor` cascades. What was the original idea behind using `currentColor`? According to https://stackoverflow.com/questions/11867545/change-text-color-based-on-brightness-of-the-covered-background-area `getContrastYIQ` we could just use `black` for contrasts >= 128.

What do you think?
