### ISSUE TITLE
Warning when hovering over main block inserter popover

### ISSUE THREAD

**Issue by mirka** [Automattic/isolated-block-editor#81]
## Steps to reproduce

In the Storybook build:

1. Click the main block inserter button.
2. Hover over the icons in the popover body.
3. Editor crashes.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'styles')
```

**Comment by johngodley** [comment]
I think this is the same problem:

https://github.com/Automattic/p2/pull/3659

For storybook we'll need to replicate what the WP core functions `wp_add_iframed_editor_assets_html` and `should_load_block_editor_scripts_and_styles` do so that `__editorAssets` is defined on `window`.

I haven't checked but something like this may be sufficient:

```js
window.__editorAssets = {styles:"",scripts:""}
```

I don't think it's important that any styles are defined, just that the global exists.

There could still be error logged after this fix, but this is tracked here:

https://github.com/Automattic/p2/issues/3656

I think Gutenberg will downgrade them to warnings soon.

**Comment by johngodley** [comment]
Thinking about this some more it's probably something that the isolated block editor should do, in some way, but still allow the client to use the WP functions.

For now though, probably easiest to jam it in storybook.

**Comment by mirka** [comment]
With the latest `@wordpress` packages for Gutenberg 11.7 (#82), the crash is averted, and instead of the previous error we get a console warning:

```
traverse.js:25 Error while traversing the CSS: TypeError: Cannot read properties of undefined (reading 'slice')
```

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/utils/transform-styles/traverse.js

Functionality does not seem to be affected.
